### ISSUE TITLE
References wrong

### ISSUE THREAD

**Issue by royvandijk06** [PerimeterX/flast#8]
Here is a quick example:
https://runkit.com/royvandijk06/62eeba06b76136000866ef26

![image](https://user-images.githubusercontent.com/15157079/183262514-41814a34-f418-42dd-b737-d99ccec89ab4.png)

The last `sid` is a whole new variable and is NOT a reference of the previous `sid`'s .
Scope issue?

**Comment by royvandijk06** [comment]
Btw, this projects is great! It provides a much more usable datastructure than `eslint-scope` does.

**Comment by BenBaryoPX** [comment]
Definitely a scope issue. Thanks for reporting!
Following this I'm overhauling the scoping to cover this and other edge cases I've encountered.
I'll also be improving the tests so they'll cover more cases.
I've seen your PR and be getting to it right after I'm done with this issue.
Thanks again for taking the time to open an issue and a PR 🙏🙂

**Comment by BenBaryoPX** [comment]
As I wrote a couple of hours ago, I overhauled the scoping and covered this case.
I've also taken into account issue #10, and have already merged them into main.
I really appreciate the time and effort you've put into opening the issues and PRs.

Please reopen any issue if you find they still persist.

**Comment by royvandijk06** [comment]
Looks like the issue from my example is resolved now, thank you!

I don't know if this is intended, but only the `declNode` has `references`, but none of the references have the property `references`.  Actually, this is not a bad design.

**Comment by BenBaryoPX** [comment]
Yes this is intentional. If an identifier has a `declNode` property it means it is a reference. 
If it has a `references` property - it is an identifier declared in the script.
If it has neither - it is not defined in the script (like `window` or `process`).

**Comment by royvandijk06** [comment]
> Yes this is intentional. If an identifier has a `declNode` property it means it is a reference. If it has a `references` property - it is an identifier declared in the script. If it has neither - it is not defined in the script (like `window` or `process`).

Btw, might be worth mentioning this in the docs.
